import { Investor, Startup, Talent } from './types';

export const startups: Startup[] = [
  {
    id: 's1',
    name: 'EcoTrack',
    tagline: "L'empreinte carbone simplifiée pour les entreprises.",
    description: "EcoTrack développe une solution SaaS permettant aux PME de mesurer, réduire et compenser leur empreinte carbone en temps réel grâce à l'IA.",
    industry: 'Greentech',
    fundingGoal: 500000,
    raised: 150000,
    logoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=80&w=800',
    openRoles: ['Développeur Full-Stack', 'Data Scientist', 'Commercial B2B'],
    images: [
      'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800'
    ],
    team: [
      { id: 'tm1', name: 'Alice Renard', role: 'CEO & Cofounder', type: 'cofounder', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200' },
      { id: 'tm2', name: 'Paul Bernard', role: 'CTO & Cofounder', type: 'cofounder', avatarUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=200' },
      { id: 'tm3', name: 'Sophie Martin', role: 'Lead Designer', type: 'employee', avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=200' },
      { id: 'tm4', name: 'Hugo Dubois', role: 'Data Scientist', type: 'employee', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200' },
      { id: 'tm5', name: 'Jean Dupont', role: 'Advisor', type: 'associate', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200' },
      { id: 'tm6', name: 'BPI France', role: 'Partenaire Financier', type: 'partner', avatarUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=200' },
    ],
    metrics: [
      { label: 'Création', value: '2023' },
      { label: 'Siège', value: 'Paris, France' },
      { label: 'Secteur', value: 'Greentech' },
      { label: 'Stade', value: 'Amorçage' },
    ],
    investorData: {
      capitalSocial: '10 000 MRU',
      users: '+15 000 utilisateurs actifs',
      growthRate: '+25% de croissance mensuelle (MoM)',
      revenue: '120 000 MRU de CA sur les 12 derniers mois',
      teamSize: 'Équipe de 6 collaborateurs',
      marketSize: 'Marché cible de 2 milliards d\'euros',
    }
  },
  {
    id: 's2',
    name: 'MediSync',
    tagline: "Le carnet de santé numérique sécurisé.",
    description: "Une application mobile unifiant les dossiers médicaux des patients et facilitant la communication avec les professionnels de santé.",
    industry: 'HealthTech',
    fundingGoal: 1200000,
    raised: 800000,
    logoUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800',
    openRoles: ['Product Manager', 'Développeur Mobile iOS'],
    stage: 'Amorçage',
    investorData: {
      capitalSocial: '15 000 MRU',
      users: '+50 établissements de santé',
      growthRate: '+15% de croissance mensuelle (MoM)',
      revenue: '85 000 MRU d\'ARR',
      teamSize: 'Équipe de 4 collaborateurs',
      marketSize: 'Marché cible de 1.5 milliards d\'euros',
    }
  },
  {
    id: 's3',
    name: 'FinFlow',
    tagline: "La trésorerie prédictive pour les startups.",
    description: "Plateforme de gestion financière automatisée qui aide les jeunes entreprises à gérer leur cash-flow et à prévoir leurs dépenses.",
    industry: 'Fintech',
    fundingGoal: 300000,
    raised: 50000,
    logoUrl: 'https://media.licdn.com/dms/image/v2/D4D12AQEZ1aNiiwhBSA/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1693477361844?e=2147483647&v=beta&t=l4vSy2bJbssYr4xlsvLk0w30UbuRC9qIdu_1fsBbPeE',
    openRoles: ['UX/UI Designer', 'Ingénieur Backend'],
    stage: 'Idéation',
  },
  {
    id: 's4',
    name: 'AgriSense',
    tagline: "L'agriculture de précision par drone.",
    description: "Des drones autonomes analysent les cultures pour optimiser l'irrigation et réduire l'usage de pesticides.",
    industry: 'AgriTech',
    fundingGoal: 800000,
    raised: 450000,
    logoUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&q=80&w=800',
    openRoles: ['Pilote de Drone', 'Ingénieur Agronome'],
    stage: 'Croissance',
  },
  {
    id: 's5',
    name: 'EduSpace',
    tagline: "L'apprentissage immersif en réalité virtuelle.",
    description: "Plateforme éducative en VR pour les écoles, permettant des sorties scolaires virtuelles sur Mars ou dans l'Antiquité.",
    industry: 'EdTech',
    fundingGoal: 2000000,
    raised: 1200000,
    logoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=800',
    openRoles: ['Développeur VR', 'Game Designer', 'Professeur'],
    stage: 'Amorçage',
  },
  {
    id: 's6',
    name: 'LogiChain',
    tagline: "La blockchain au service de la logistique.",
    description: "Traçabilité transparente de la chaîne d'approvisionnement pour lutter contre la contrefaçon.",
    industry: 'Logistics',
    fundingGoal: 1500000,
    raised: 1500000,
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjecdtL9NvURdOznDEVfVFmUwv4awEtdInEoL3iEbglrOHY7G1eVEq7gbw&s=10',
    openRoles: ['Développeur Blockchain', 'Supply Chain Manager'],
    stage: 'Croissance',
  },
  {
    id: 's7',
    name: 'MindWell',
    tagline: "Le bien-être mental au travail.",
    description: "Application B2B offrant un soutien psychologique anonyme et des ressources de méditation pour les employés.",
    industry: 'HealthTech',
    fundingGoal: 400000,
    raised: 200000,
    logoUrl: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&q=80&w=800',
    openRoles: ['Psychologue clinicien', 'Customer Success'],
    stage: 'Idéation',
  },
  {
    id: 's8',
    name: 'CodeAI',
    tagline: "Votre assistant de programmation IA.",
    description: "Générez du code, trouvez des bugs et optimisez vos applications avec notre IA spécialisée pour les développeurs.",
    industry: 'IA',
    fundingGoal: 3000000,
    raised: 500000,
    logoUrl: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&q=80&w=800',
    openRoles: ['Ingénieur IA', 'Développeur Front-End'],
    stage: 'Amorçage',
  },
  {
    id: 's9',
    name: 'Solaris',
    tagline: "Panneaux solaires ultra-fins et flexibles.",
    description: "Nouvelle génération de panneaux solaires pouvant s'intégrer sur n'importe quelle surface urbaine.",
    industry: 'Greentech',
    fundingGoal: 5000000,
    raised: 2500000,
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtDY8l7Je8y-Ybcqlp5K0Fw_W8hETgAI0gBCjC9ilKoYbJM20awYbgm2Yk&s=10',
    openRoles: ['Ingénieur Matériaux', 'Directeur des Ventes'],
    stage: 'Croissance',
  },
  {
    id: 's10',
    name: 'CyberShield',
    tagline: "Protection proactive contre les ransomwares.",
    description: "Solution de cybersécurité qui détecte et bloque les attaques avant qu'elles ne chiffrent vos données.",
    industry: 'Cybersécurité',
    fundingGoal: 2500000,
    raised: 1800000,
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800',
    openRoles: ['Analyste SOC', 'Ingénieur Sécurité'],
    stage: 'Idéation',
  },
  {
    id: 's11',
    name: 'NutriTech',
    tagline: "L'alimentation personnalisée par l'ADN.",
    description: "Des recommandations nutritionnelles basées sur votre profil génétique pour une santé optimale.",
    industry: 'FoodTech',
    fundingGoal: 1000000,
    raised: 750000,
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5u95lTX_CClRsdDsZ4rk9jaurFvgMXDMZc7iP_dNTJrmyRuB47nY3Ouou&s=10',
    openRoles: ['Généticien', 'Diététicien'],
    stage: 'Amorçage',
  },
  {
    id: 's12',
    name: 'AutoDrive',
    tagline: "Logiciel de conduite autonome open-source.",
    description: "Démocratiser la conduite autonome avec une plateforme ouverte pour les constructeurs automobiles.",
    industry: 'Mobility',
    fundingGoal: 10000000,
    raised: 8000000,
    logoUrl: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=800',
    openRoles: ['Ingénieur Vision par Ordinateur', 'Développeur C++'],
    stage: 'Croissance',
  }
];

export const investors: Investor[] = [
  {
    id: 'i1',
    name: 'Julien Roche',
    type: 'particulier',
    subtitle: 'Business angel · Ex-fondateur SaaS',
    verified: true,
    focus: ['Fintech', 'Greentech', 'SaaS B2B'],
    stages: ['Pre-seed', 'Seed'],
    bio: "A revendu sa startup logistique en 2022. Investit à titre personnel dans des SaaS B2B early-stage.",
    about: "Ancien ingénieur devenu entrepreneur, j'ai fondé et revendu deux entreprises dans la logistique et le SaaS B2B. Aujourd'hui, j'accompagne de jeunes fondateurs ambitieux en phase d'amorçage. Au-delà de l'apport financier, je m'implique fortement sur les volets produit, go-to-market et structuration de l'équipe tech. Je recherche des équipes résilientes, obsédées par leur marché et capables d'itérer très vite.",
    investmentRange: 'Ticket 3 500 € moy.',
    totalInvested: '86 000 €',
    avgTicket: '3 500 €',
    coverUrl: 'https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&q=80&w=800',
    location: 'Paris, France',
    portfolioCount: 9,
    socialLinks: { linkedin: 'julienroche', twitter: 'jroche_invest' },
    portfolio: [
      { name: 'EcoTrack', industry: 'Greentech', logoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=80&w=200', url: 'ecotrack.io' },
      { name: 'PayFlow', industry: 'Fintech', logoUrl: 'https://images.unsplash.com/photo-1559526324-593bc073d938?auto=format&fit=crop&q=80&w=200' },
      { name: 'DataSync', industry: 'SaaS B2B', logoUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=200' }
    ]
  },
  {
    id: 'i2',
    name: 'Impact Ventures',
    type: 'entreprise_fonds',
    subtitle: 'Fonds d\'investissement à impact',
    verified: true,
    focus: ['HealthTech', 'Greentech', 'Impact', 'EdTech'],
    stages: ['Seed', 'Série A'],
    bio: "Fonds d'investissement engagé. Nous cherchons à financer les innovations qui améliorent la vie et protègent la planète, avec une approche centrée sur l'ESG.",
    about: "Impact Ventures est un fonds de dotation de 50M€ dédié aux startups à fort impact social et environnemental. Notre thèse d'investissement repose sur la conviction que les entreprises les plus rentables de demain seront celles qui résolvent les défis fondamentaux de notre époque. Nous investissons des tickets allant de 200k€ à 1M€, majoritairement en tant que lead investor lors des tours de Seed ou Série A.",
    investmentRange: 'Tickets de 200k€ à 1M€',
    totalInvested: '12M €',
    avgTicket: '500 000 €',
    avatarUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=80&w=200',
    coverUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&q=80&w=800',
    location: 'Nouakchott, Mauritanie',
    website: 'impact-ventures.mru',
    portfolioCount: 15,
    socialLinks: { linkedin: 'impact-ventures' },
    team: [
      { name: 'Amadou Fall', role: 'Managing Partner', avatarUrl: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?auto=format&fit=crop&q=80&w=200', linkedin: 'amadoufall' },
      { name: 'Sophie Diallo', role: 'Investment Principal', avatarUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=200', linkedin: 'sophiediallo' }
    ],
    portfolio: [
      { name: 'AgriSense', industry: 'AgriTech', logoUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&q=80&w=200' },
      { name: 'Solaris', industry: 'Greentech', logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtDY8l7Je8y-Ybcqlp5K0Fw_W8hETgAI0gBCjC9ilKoYbJM20awYbgm2Yk&s=10' }
    ]
  },
  {
    id: 'i3',
    name: 'Capital Innovation',
    type: 'entreprise_fonds',
    subtitle: 'Seed fund spécialisé DeepTech',
    verified: false,
    focus: ['IA', 'Cybersécurité', 'DeepTech', 'Quantique'],
    stages: ['Pre-seed', 'Seed'],
    bio: "Fonds d'amorçage spécialisé dans les technologies de rupture et la deeptech. Nous soutenons les chercheurs et ingénieurs visionnaires depuis la genèse de leur projet.",
    about: "Nous sommes un fonds composé exclusivement d'anciens chercheurs et ingénieurs. Notre mission est de faire le pont entre la recherche académique et le monde de l'entreprise. Nous n'avons pas peur du risque technologique ou des temps de développement longs. Nous finançons les premières étapes de l'industrialisation, le dépôt de brevets et les premiers POC industriels.",
    investmentRange: 'Tickets 500k€ - 2M€',
    totalInvested: '25M €',
    avgTicket: '1M €',
    avatarUrl: 'https://images.unsplash.com/photo-1616423640778-28d1b53229bd?auto=format&fit=crop&q=80&w=200',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800',
    location: 'Dakar, Sénégal',
    website: 'capital-inno.vc',
    portfolioCount: 32,
    team: [
      { name: 'Dr. Jean-Marc Blanc', role: 'Partner & IA Expert', avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200' },
      { name: 'Cécile Ndiaye', role: 'Venture Partner', avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200' }
    ]
  },
  {
    id: 'i4',
    name: 'Sophie Laurent',
    type: 'particulier',
    subtitle: 'Executive Tech & Angel Investor',
    verified: true,
    focus: ['EdTech', 'AgriTech', 'Future of Work'],
    stages: ['Seed'],
    bio: "Executive dans la tech reconvertie en investisseuse. J'apporte mon réseau et mon expertise opérationnelle pour accélérer le développement des projets ambitieux.",
    about: "Après 15 ans passés à des postes de direction dans de grandes entreprises technologiques, je me consacre désormais au développement de l'écosystème startup. J'investis des tickets de 10k€ à 20k€ dans des projets ayant déjà une première traction ou un prototype fonctionnel. Mon objectif est d'aider les fondateurs à structurer leur croissance, recruter leurs premiers talents clés et préparer leur levée de fonds institutionnelle.",
    investmentRange: 'Ticket 15 000 € moy.',
    totalInvested: '120 000 €',
    avgTicket: '15 000 €',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    coverUrl: 'https://images.unsplash.com/photo-1491895200222-0fc4a4c35e18?auto=format&fit=crop&q=80&w=800',
    location: 'Lyon, France',
    portfolioCount: 4,
    socialLinks: { linkedin: 'sophielaurent' },
    portfolio: [
      { name: 'EduSpace', industry: 'EdTech', logoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=200' }
    ]
  }
];

export const talents: Talent[] = [
  {
    id: 't1',
    name: 'Thomas Leroy',
    title: 'Développeur Full-Stack Senior',
    skills: ['React', 'Node.js', 'TypeScript', 'AWS'],
    bio: "5 ans d'expérience en création d'applications SaaS. Je cherche un projet stimulant avec un impact positif.",
  },
  {
    id: 't2',
    name: 'Camille Dubois',
    title: 'Data Scientist',
    skills: ['Python', 'Machine Learning', 'NLP', 'SQL'],
    bio: "Passionnée par l'analyse de données complexes. Expérience précédente dans la Fintech.",
  },
  {
    id: 't3',
    name: 'Lucas Martin',
    title: 'UX/UI Designer',
    skills: ['Figma', 'Prototyping', 'User Research', 'Design Systems'],
    bio: "Je conçois des interfaces intuitives et esthétiques. J'aime transformer des problèmes complexes en expériences simples.",
  },
  {
    id: 't4',
    name: 'Julie Rivière',
    title: 'Directrice Marketing (CMO)',
    skills: ['Growth Hacking', 'SEO', 'Brand Strategy', 'B2B Marketing'],
    bio: "Experte en stratégie d'acquisition. J'ai aidé 3 startups à passer de 0 à 1M MRU d'ARR.",
  },
];
